name: UTCS CI

on:
  push:
    branches: [ main, 'feat/**' ]
  pull_request:
    branches: [ main ]

jobs:
  lint-canon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate UTCS manifest presence
        run: test -f utcs/manifest.yaml
      
      - name: Check PAx orientation markers (OB/OFF only)
        run: |
          # Check for actual use of ONB/OUT (excluding docs that mention them as forbidden)
          if grep -RIn "^\s*ONB\|^\s*OUT\s" -- content/ 2>/dev/null | grep -v "no ONB/OUT" | grep -v "forbidden" | grep .; then
            echo "Error: Use OB/OFF only, not ONB/OUT"
            exit 1
          fi
          echo "✓ PAx orientation markers valid"
      
      - name: Enforce AMPEL360 as commons (no app code)
        run: |
          ALLOW_DIRS="ontology deontology source_data schemas contracts lineage README.md"
          echo "Checking AMPEL360/ for forbidden app code..."
          
          # Check for forbidden directory patterns
          if find AMPEL360 -maxdepth 2 -type d \( -name "src" -o -name "app" -o -name "services" -o -name "cmd" \) 2>/dev/null | grep .; then
            echo "Error: Found app-code directories in AMPEL360/"
            exit 1
          fi
          
          echo "✓ AMPEL360 contains only commons (no app code)"
      
      - name: Validate lineage registry
        run: |
          test -f AMPEL360/lineage/registry.yaml || (echo "Error: lineage registry not found" && exit 1)
          echo "✓ Lineage registry exists"
      
      - name: Validate program identity schema
        run: |
          test -f AMPEL360/schemas/program.identity.schema.json || (echo "Error: program identity schema not found" && exit 1)
          echo "✓ Program identity schema exists"
      
      - name: Validate BWB-Q100 program identity
        run: |
          test -f BWB-Q100/program.identity.json || (echo "Error: BWB-Q100 program identity not found" && exit 1)
          echo "✓ BWB-Q100 program identity exists"
      
      - name: Verify appendix G exists
        run: |
          test -f content/appendix_g_ampel360_commons.md || (echo "Error: Appendix G not found" && exit 1)
          echo "✓ Appendix G (AMPEL360 commons) exists"
  
  validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install jsonschema
        run: pip install jsonschema pyyaml
      
      - name: Validate program.identity.json against schema
        run: |
          python3 << 'EOF'
          import json
          import jsonschema
          
          # Load schema
          with open('AMPEL360/schemas/program.identity.schema.json', 'r') as f:
              schema = json.load(f)
          
          # Load BWB-Q100 identity
          with open('BWB-Q100/program.identity.json', 'r') as f:
              identity = json.load(f)
          
          # Validate
          try:
              jsonschema.validate(instance=identity, schema=schema)
              print("✓ BWB-Q100/program.identity.json validates against schema")
          except jsonschema.exceptions.ValidationError as e:
              print(f"Error: Validation failed: {e.message}")
              exit(1)
          EOF
  
  build-utcs:
    runs-on: ubuntu-latest
    needs: [lint-canon, validate-schemas]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build UTCS bundle
        run: |
          cd sheet
          make validate
          make bundle
      
      - name: Upload UTCS bundle
        uses: actions/upload-artifact@v3
        with:
          name: utcs-bundle
          path: evidence/utcs_bundles/utcs-latest.tar.gz
