name: UTCS Build & CSDB Federation

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install LaTeX dependencies
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # If you use pip for Python dependencies, add here:
      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt

      - name: Build PDF
        run: make -C sheet pdf

      - name: Build HTML
        run: make -C sheet html

      - name: Generate SBOM
        run: make -C sheet sbom

      - name: Generate Hashes
        run: make -C sheet hash

      # Optionally, upload artifacts for inspection
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: techpubs_overview_pdf
          path: cache/techpubs_overview.pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: techpubs_overview_html
          path: cache/techpubs_overview.html

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: evidence/sbom.spdx.json

      - name: Upload Checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: evidence/checksums.sha256
