name: UTCS Build & CSDB Federation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TeX Live (for pdflatex)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Optional: Install dependencies if requirements.txt exists
      - name: Install Python dependencies (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi

      - name: Build PDF
        working-directory: ./sheet
        run: make pdf
